# Site wide configuration
title: "캡틴판교"
description: "Learn, code and sing"
logo: share_logo.png # 120x120 px default image used for Twitter summary card
# teaser image is 400x250px
teaser: # 400x250 px default teaser image used in image archive grid
locale: "ko_KR"
# change this url with localhost:4000 in dev
url: https://joshua1988.github.io
# url: http://localhost:4000
feed:
  path: atom.xml

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
  # https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#syntax-highlighting
  syntax_highlighter_opts:
    disable: true
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Site owner
owner:
  name:
  email: jangkeehyo@gmail.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio: Captain Pangyo
  avatar: josh.png # 160x160 px image for author byline
  disqus-shortname: captain-pangyo

include: ["_pages"]
# include:
#   - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
